## 11. ナイーブベイズ

In [3]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
features = iris.data
target = iris.target

classifer = GaussianNB()
classifer_proir = GaussianNB(priors=[0.25,0.25,0.5])

model = classifer.fit(features, target)
model_proir = classifer_proir.fit(features, target)

In [4]:
new_observation = [[4,4,4,0.4]]

print(model.predict(new_observation))
print(model_proir.predict(new_observation))

[1]
[1]


離散特徴量とカウント特徴量  
多項ナイーブベイズ

In [6]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

text_data = np.array(['I have an apple',
                      'I have a pen',
                      'pen pineapple apple pen'])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

features = bag_of_words.toarray()

target = np.array([0,0,1])

classifer = MultinomialNB(class_prior=[0.25,0.5])

model = classifer.fit(features, target)

In [8]:
new_obsevation = [[0,1,0,1,0]]

model.predict(new_obsevation)

array([1])

2クラス特徴量に対するnb

In [12]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

features = np.random.randint(2, size=(100, 3))

target = np.random.randint(2, size=(100, 1)).ravel()

classifer = BernoulliNB(class_prior=[0.25, 0.5], alpha=0.5) # alpha 平滑化パラメータ

model = classifer.fit(features, target)

In [13]:
new_obsevation = [[0,1,0]]

model.predict(new_obsevation)

array([1])

予測確率の較正

In [15]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV

iris = datasets.load_iris()
features = iris.data
target = iris.target

classifer = GaussianNB()

classifer_sigmoid = CalibratedClassifierCV(classifer, cv=2, method="sigmoid")

classifer_sigmoid.fit(features, target)

new_observation = [[2.6, 2.6, 2.6, 0.4]]

classifer_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])